config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  devise_scope :user do get "/registrations/show" => "registrations_controller"
  end
  root to: "home#index"

  resources :tests do
    collection do
      get :activate_test
      get :deactivate_test
      get :current_exam
      post :submit_exam
      get :autocomplete_student_name
      get :search
    end
  end
  resources :multiple_choice_questions
  resources :descriptive_questions

end

app/views/shared/_banner.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner container-fluid">
    <div class="col-sm-12">
      <div class="navbar-header">
        <div class="navbar-brand">
          <%= link_to (image_tag "logo.jpg", :alt => "Logo Here", :height => "41px"), root_path %>
        </div>
      </div>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Home", root_path %>
        </li>
<!--         <li>
          <%#= link_to "About", "#" %>
        </li> -->
        
<!--         <li>
          <%#= link_to "Contact", "#" %>
        </li> -->
        <% if current_user.present? %>
         
          <% if current_user.teacher? %>
            <%= render "shared/teacher_side_bar" %>
 
              <% else %>
            <%= render "shared/student_side_bar" %>
                <% end %>

                 <li>
            <%= link_to "View Profile", registrations_show_path %>
          </li>

          <li>
            <%= link_to "Sign-Out", destroy_user_session_path, :data => {:method => :delete} %>
          </li>
         
        <% else %>
          <li>
            <%= link_to "Sign-IN", new_user_session_path %>
          </li>
     <!--      <li>
            <%#= link_to "Registration", new_user_registration_path %>
          </li> -->
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<ul class="nav">
  <% object.errors.full_messages.each do |message| %>
    <li class="alert alert-danger">
      <%= message %>
    </li>
  <% end %>
</ul>

app/views/shared/_side_bar.html.erb
<%# if current_user.teacher? %>
<%#= render "shared/teacher_side_bar" %>
 
<%# else %>
   <%#= render "shared/student_side_bar" %>
<%#end %>

app/views/shared/_student_side_bar.html.erb
<ul  class="nav navbar-nav">
  <li class="active">
    <%= link_to "Current Exam", current_exam_tests_path %>
  </li>
  <!-- <li> -->
  <!--   <%= link_to "Reports", "#" %> -->
  <!-- </li> -->
</ul>

app/views/shared/_teacher_side_bar.html.erb
<ul  class="nav navbar-nav">
  <!-- <li > -->
  <!--   <%= link_to "All Quizs", tests_path %> -->
  <!-- </li> -->
  <li >
    <%= link_to "New Quiz", new_test_path %>
  </li>
<!--   <li>
  </li> -->
  <!-- <li> -->
  <!--   <%= link_to "Reports", "#" %> -->
  <!-- </li> -->
</ul>