config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  devise_scope :user do get "/registrations/show" => "registrations_controller"
  end
  root to: "home#index"

  resources :tests do
    collection do
      get :activate_test
      get :deactivate_test
      get :current_exam
      post :submit_exam
      get :autocomplete_student_name
      get :search
    end
  end
  resources :multiple_choice_questions
  resources :descriptive_questions

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check

  def index
    if current_user.present?
      if current_user.teacher?
        @tests = Test.all
        @report_tests = StudentTest.select(:test_id).uniq
        
        render "teacher_index"
      elsif current_user.student?
        @current_test_id = Test.find_by_status("activated")
        if Test.find_by_status("activated") and !StudentTest.where(status: "completed", user_id: current_user.id, test_id: @current_test_id).present?
          @current_test = Test.find(@current_test_id)
        else
          @current_test_id = nil
        end
        @student_completed_tests = StudentTest.where(status: "completed", user_id: current_user.id).order("created_at ASC")
      end    
    end
    
  end

end

app/views/home/index.html.erb
<% if current_user.present? %>
<div class="page-header">
  <h2>Current Exam</h2>
</div>
<% if @current_test_id.present? %>
<div class="col-md-12">
  <div class="col-md-3">
    <button type="button" disabled="true" class='btn btn-large btn-info'><%= @current_test.test_name %></button>
  </div>

  <div class="col-md-3">
    <%= button_to "Take" , current_exam_tests_path, :method => :get, :class => 'btn btn-large btn-info'%>
  </div>
</div>
<% else %>
<div class="col-md-12">
  <button type="button" disabled="true" class='btn btn-large btn-warning'>Present No Exam Scheduled!</button>
</div>
<% end %>



<div class="page-header">
  <h2>Past Exams</h2>
</div>
  <% if @student_completed_tests.present? %>
  <% @student_completed_tests.each_with_index do |student_completd_test,index| %>
  <div class="col-md-12">
    <div class="col-md-3">
      <button type="button" disabled="true" class='btn btn-large btn-info'><%= student_completd_test.test.test_name%></button>
    </div>

    <div class="col-md-3">
      <%= button_to "view Report" , test_path(student_completd_test.test.id), :method => :get, :class => 'btn btn-large btn-info'%>
    </div>
  </div>
  <% end %>
  <% else %>
  <div class="col-md-12">
    <button type="button" disabled="true" class='btn btn-large btn-warning'>There is No Past Exams!</button>
  </div>
  <% end %>
</div>

<% end %>

app/views/home/teacher_index.html.erb
<div class="page-header">
  <h2>Tests</h2>
</div>

<table class="table table-bordered table-hover">
  <tbody>
    <% @tests.each_with_index do |test,index| %>
    <tr>
      <td>
        <%= link_to test.test_name, test %>
      </td>
      <% if test.status == "activated" %>
      <td>
        <%= button_to "Deactive", deactivate_test_tests_path, method: :get, params: {test_id: test.id}, :class => 'btn btn-large btn-warning'%>
      </td>
      <% elsif test.status == "deactivated" %>
      <td>
        <%= button_to "Activate", activate_test_tests_path, method: :get, params: {test_id: test.id}, :class => 'btn btn-large btn-primary'%>
      </td>
      <% end %>
      <% end %>
  </tbody>
</table>


<div class="page-header">
  <h2>Reports</h2>
</div>

<table class="table table-bordered table-hover">
  <tbody>
    <% @report_tests.each_with_index do |report_test,index| %>
    <tr>
      <td>
        <%= link_to report_test.test.test_name, "/tests/#{report_test.test_id}?report=true" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>